### PR TITLE
Add SatisfiesParameter to Validate.Param and Validate.ParamCollection

### PR DESCRIPTION
**Pull request by LibraChris**
Introduce SatisfiesParameter as a validation method for Param and ParamCollection, alongside foundational tests for both functionalities.

### CODE REVIEW

**Comment by omaus** [comment]
Could it be that `Validate.ParamCollection.SatisfiesParameter` is the same like the function in this PR?: #88 🤔

**Comment by LibraChris** [comment]
> Could it be that `Validate.ParamCollection.SatisfiesParameter` is the same like the function in this PR?: #88 🤔

No, since your function checks each element against a condition, while mine just checks if a certain function on the Params returns true. So, for example, using Seq.exist would return true if just one element of the ParamCollection matches.

**Comment by omaus** [comment]
Could it be that `Validate.ParamCollection.SatisfiesParameter` is the same like the function in this PR?: #88 🤔

> > Could it be that `Validate.ParamCollection.SatisfiesParameter` is the same like the function in this PR?: #88 🤔
> 
> No, since your function checks each element against a condition, while mine just checks if a certain function on the Params returns true. So, for example, using Seq.exist would return true if just one element of the ParamCollection matches.

Ah okay, I get it. Thx! 👍

**Review by kMutagene — APPROVED** [review]

**Comment by kMutagene** [comment]
Let's incorporate the spec validation directly into the lib, after dependency updates and this is merged 👍

**Pull request merged**
